/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vpotry' at '18.9.2015 14:21' with Gradle 2.3
 *
 * @author vpotry, @date 18.9.2015 14:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
